language: python
sudo: required
addons:
  apt_packages:
    - pandoc
cache:
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/build/amn41/rasa_core/data"
python:
- '2.7'
- '3.6'
install:
- sudo apt-get update
- if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh
  -O miniconda.sh; else wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
  -O miniconda.sh; fi
- bash miniconda.sh -b -f -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a
- conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION scipy=0.19.0 numpy=1.12.1
  scikit-learn=0.18.1
- source activate test-environment
- pip install pypandoc==1.4
- pip install -r dev-requirements.txt
- pip install spacy sklearn-crfsuite==0.3.5
- pip install https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-1.2.0/en_core_web_sm-1.2.0.tar.gz
  --no-cache-dir > jnk
- python -m spacy link en_core_web_sm en
- pip install -e .
- pip list
script:
- travis_wait py.test tests --cov rasa_core --pep8 -v
# - cd docs && make doctest   # can't do yet - doctests need to be cleaned up first
after_success:
- openssl aes-256-cbc -K $encrypted_050c822e99ef_key -iv $encrypted_050c822e99ef_iv
  -in docs/key.enc -out docs/key -d
- coveralls
jobs:
  include:
  - stage: docs
    install:
    - sudo apt-get update
    - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh
      -O miniconda.sh; else wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
      -O miniconda.sh; fi
    - bash miniconda.sh -b -f -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a
    - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION scipy=0.19.0 numpy=1.12.1
      scikit-learn=0.18.1
    - source activate test-environment
    - pip install sphinx==1.5.2 sphinx-autobuild==0.6.0 sphinxcontrib-versioning==2.2.1 sphinxcontrib-httpdomain==1.5.0
      nbsphinx==0.2.13
    - pip install -e git://github.com/RasaHQ/sphinx_rtd_theme.git#egg=sphinx_rtd_theme
    - pip install -e .
    script:
    - eval "$(ssh-agent -s)"; touch docs/key; chmod 0600 docs/key
    - openssl aes-256-cbc -K $encrypted_050c822e99ef_key -iv $encrypted_050c822e99ef_iv
      -in docs/key.enc -out docs/key -d && ssh-add docs/key
    - git config --global user.email "builds@travis-ci.com"
    - git config --global user.name "Travis CI"
    - git remote set-url --push origin "git@github.com:$TRAVIS_REPO_SLUG"
    - export ${!TRAVIS*}
    - sphinx-versioning push docs gh-pages .
  - stage: deploy
    install:
    - pip install pypandoc==1.4
    script: skip
    deploy:
      provider: pypi
      user: amn41
      on:
        branch: master
        tags: true
      password:
        secure: kiTlDDc29TQST6ZUsOEo6CAjz9TOsnpXeQ/gGyLBUKR039KBaseU6YCYL5QfPtYtOsiYp981AGO55Kn0lSwmDvNWXz1N7XcBA5JeSgAQo/uq8uvSwOsPVoMNzSKir9y4A8ZIsLr9R6iTBCFw0Yvvcarvay1FgG+rwwjGVGKsqlRmggo7a8G+DgNhmacYkBYIugjJ/jfs4bNCqpLP7tmYfhxIqICbma562APkGNP5fjo0cMgzittR/OIpo5iyeV63EWio4oyU2Y3Kw69L4yx4sIBbrIbFYT5LdgD0l3aMNbh4Ne9GrGmt/pw94cjxCNxspxNeqZhkG+CXq2/bQSPdH/DW4eH/1ac9d9TO/WC7FaobqamltDldqgJqRAnjT6OZsRU2lZlyHurBvobWcksbZ4pdCwYNDt2pKGVk66FqxVFGp6SZCw+wnwwIaO7sI4FLIfQ1BTp+imYlWead79JgFmGyo2of5xM2TSkcFjaS4KUJ45zmDYLrKb1n2dcfzs0dRRIKbbCPcGBBC1mcHfV/EOYMlFzXD432LR9cZf/sr4f2yt0gDhqtzDMmwtj1bvH0ji/9sI7lXioMiOMkV4rqE/XEdXfxRTGSLKpuD8adLRNekEV2zk2uyTiVBJcQKZThwS/qkG8lDBUAHqvz89d+Vo/84bErWd05GtdDgwNWBzM=
